-- Tạo DB và bảng cho Bài 3
CREATE DATABASE IF NOT EXISTS newsdb CHARACTER SET utf8mb4;
USE newsdb;

CREATE TABLE IF NOT EXISTS DANHMUC (
  MADM INT PRIMARY KEY AUTO_INCREMENT,
  TENDANHMUC VARCHAR(100) NOT NULL,
  NGUOIQUANLY VARCHAR(100),
  GHICHU VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TINTUC (
  MATT INT PRIMARY KEY AUTO_INCREMENT,
  TIEUDE VARCHAR(150) NOT NULL,
  NOIDUNGTT VARCHAR(255) NOT NULL,
  LIENKET VARCHAR(255) NOT NULL,
  MADM INT NOT NULL,
  FOREIGN KEY (MADM) REFERENCES DANHMUC(MADM) ON DELETE CASCADE
);

INSERT INTO DANHMUC (TENDANHMUC, NGUOIQUANLY, GHICHU)
VALUES ('Thể thao','Anh A',NULL),('Công nghệ','Chị B',NULL)
ON DUPLICATE KEY UPDATE TENDANHMUC=VALUES(TENDANHMUC);

INSERT INTO TINTUC (TIEUDE, NOIDUNGTT, LIENKET, MADM)
VALUES ('Tin 1','Nội dung 1','http://example.com/1',1),
       ('Tin 2','Nội dung 2','http://example.com/2',2);
